root = "."
tmp_dir = "tmp/air"

[build]
  cmd = "go build -o bin/easi ./cmd/easi"
  entrypoint = ["bin/easi", "serve"]
  include_ext = ["go", "sql"]
  include_dir = ["cmd", "pkg"]
  log = "air.log"
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = "500ms"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true