---
version: '3.7'
services:
  db_migrate:
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-db-migrate:${CIRCLE_SHA1}'
  easi:
    image: '${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-backend:${CIRCLE_SHA1}'
    environment:
      - EMAIL_TEMPLATE_DIR=/easi/templates
      - SERVER_CERT
      - SERVER_KEY
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client_circleci
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ['serve', '-s', '-l', '3000']
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: easi-cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
    network_mode: 'service:easi_client'
    depends_on:
      - easi_client
