---
version: '3.7'
services:
  db:
    ports:
      - 5432:5432
  db_migrate:
    build:
      context: .
      dockerfile: Dockerfile.db_migrations
    volumes:
      - ./migrations:/flyway/sql
  db_seed:
    build:
      context: .
      dockerfile: Dockerfile.db_seed
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
  easi:
    build:
      context: .
      dockerfile: Dockerfile
    image: easi-backend:latest
    environment:
      - APP_ENV=test
      - EMAIL_TEMPLATE_DIR=/easi/templates
      - FLAG_SOURCE=FILE
      - FLAGDATA_FILE=/cypress/fixtures/flagdata.json
      - LOCAL_AUTH_ENABLED=true
    ports:
      - 8080:8080
    # Mounted so that the backend container can access the file with LaunchDarkly flag values
    volumes:
      - ./cypress:/cypress
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_APP_ENV=test
        - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
        - REACT_APP_GRAPHQL_ADDRESS=http://easi:8080/api/graph/query
        - REACT_APP_OKTA_CLIENT_ID
        - REACT_APP_OKTA_DOMAIN
        - REACT_APP_OKTA_ISSUER
        - REACT_APP_OKTA_REDIRECT_URI
        - REACT_APP_OKTA_SERVER_ID
        - REACT_APP_LOCAL_AUTH_ENABLED=true
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ['serve', '-s', '-l', '3000']
    ports:
      - 3000:3000
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: easi-cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
      - REACT_APP_GRAPHQL_ADDRESS=http://easi:8080/api/graph/query
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_HOST=minio:9000
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
      - CYPRESS_MAILCATCHER_API_ADDRESS=http://email:1080
      - CYPRESS_GRT_EMAIL=success@simulator.amazonses.com # should be the same value as GRT_EMAIL in docker-compose.yml
    network_mode: 'service:easi_client'
    volumes:
      - ./cypress:/cypress
    depends_on:
      - easi_client
