---
version: '3.7'
services:
  db_migrate:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-db-migrate:${CIRCLE_SHA1}"
  easi:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-backend:${CIRCLE_SHA1}"
    environment:
      - APPLICATION_VERSION
      - APPLICATION_DATETIME
      - APPLICATION_TS
      - APP_ENV
      - CLIENT_PROTOCOL=http
      - CLIENT_DOMAIN=localhost
      - CLIENT_PORT=3000
      - CLIENT_HOSTNAME=localhost:3000
      - CLIENT_ADDRESS=http://localhost:3000
      - API_PORT=8080
      - OKTA_CLIENT_ID=0oa2e913coDQeG19S297
      - OKTA_ISSUER=https://test.idp.idm.cms.gov/oauth2/aus2e96etlbFPnBHt297
      - GRT_EMAIL=success@simulator.amazonses.com
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SES_SOURCE=no-reply-$APP_ENV@info.easi.cms.gov
      - AWS_SES_SOURCE_ARN
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=""
      - PGSSLMODE=disable
    entrypoint: ["/easi/easi", "serve"]
    depends_on:
      - db_migrate
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_APP_ENV=$APP_ENV
        - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
        - REACT_APP_OKTA_CLIENT_ID=$OKTA_CLIENT_ID_DEV
        - REACT_APP_OKTA_DOMAIN=$OKTA_DOMAIN
        - REACT_APP_OKTA_ISSUER=$OKTA_ISSUER
        - REACT_APP_OKTA_REDIRECT_URI=http://localhost:3000/implicit/callback
        - REACT_APP_OKTA_SERVER_ID=$OKTA_SERVER_ID_DEV
    image: easi-frontend:latest
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ["serve", "-s", "-l", "3000"]
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: easi-cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
    network_mode: "service:easi_client"
    depends_on:
     - easi_client
